version: '3.8'

services:
  mysql-container:
    image: mysql:8.0.13
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis-container:
    image: redis:7.4.1
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

  product-management-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-management-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql-container
      - redis-container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
