name: Push to Docker CICD Flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-java:
    name: Build Java Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test Application
      run: mvn clean install
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: 3306
        MYSQL_DATABASE: productdb
        MYSQL_USER: root
        MYSQL_PASSWORD: root

    - name: Save Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: target/

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build-java

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-assignment:product-management-api-cicd .
        docker tag ${{ secrets.DOCKER_USERNAME }}/docker-assignment:product-management-api-cicd ${{ secrets.DOCKER_USERNAME }}/docker-assignment:latest

    - name: Save Docker Image as Artifact
      run: docker save ${{ secrets.DOCKER_USERNAME }}/docker-assignment:product-management-api-cicd | gzip > docker-image.tar.gz
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: docker-image.tar.gz

  push-docker:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
    - name: Download Docker Image Artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image

    - name: Load Docker Image
      run: gunzip -c docker-image.tar.gz | docker load

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/docker-assignment:product-management-api-cicd
        docker push ${{ secrets.DOCKER_USERNAME }}/docker-assignment:latest
